CREATE TABLE tb_cadastro
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    ranking    VARCHAR(100),
    img        VARCHAR(255),
    idade      INT          NOT NULL,
    missoes_id BIGINT,
    CONSTRAINT fk_ninja_on_missoes
        FOREIGN KEY (missoes_id)
            REFERENCES missoes (id_missoes)
);